
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nijfrkcezdhyxjqotgbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pamZya2NlemRoeXhqcW90Z2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTg1OTUsImV4cCI6MjA2MzA3NDU5NX0.MAcG3S1x3E6OFFmTAg9rRJbXZYJyoI_OFw8uvjVdAHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
